import { 
  Calculator, 
  Leaf, 
  Sigma, 
  Palette, 
  Dna, 
  Briefcase, 
  FlaskRound, 
  Scroll, 
  Code, 
  HardHat, 
  Ruler, 
  TrendingUp, 
  Wrench, 
  BookOpen, 
  Globe, 
  Clock, 
  Home, 
  Award, 
  Music, 
  Atom, 
  Activity, 
  Zap, 
  Users, 
  Book, 
  Cpu,
  Globe2,
  type LucideIcon
} from 'lucide-react'

const subjectIconMap: Record<string, LucideIcon> = {
  'Accounting': Calculator,
  'Agricultural Science': Leaf,
  'Applied Maths': Sigma,
  'Art': Palette,
  'Biology': Dna,
  'Business': Briefcase,
  'Chemistry': FlaskRound,
  'Classical Studies': Scroll,
  'Computer Science': Code,
  'Construction Studies': HardHat,
  'Design & Communication Graphics': Ruler,
  'Economics': TrendingUp,
  'Engineering': Wrench,
  'English': BookOpen,
  'French': Globe2,
  'Geography': Globe,
  'German': Globe2,
  'History': Clock,
  'Home Economics': Home,
  'Irish': Globe2,
  'Italian': Globe2,
  'Japanese': Globe2,
  'LCVP': Award,
  'Mathematics': Calculator,
  'Music': Music,
  'Phys-Chem': Atom,
  'Physical Education': Activity,
  'Physics': Zap,
  'Politics and Society': Users,
  'Religious Education': Book,
  'Spanish': Globe2,
  'Technology': Cpu
}

export function getSubjectIcon(subjectName: string): LucideIcon {
  return subjectIconMap[subjectName] || Book
}